### ISSUE TITLE
Strange error with rust-analyzer

### ISSUE THREAD

**Issue by IndianBoy42** [ldelossa/calltree.nvim#2]
![image](https://user-images.githubusercontent.com/5981889/142380248-069cf0a2-89dc-43b5-9707-6f6a52ec447a.png)

I get notifications about 'file not found' whenever I move the cursor in the call tree window

**Comment by ldelossa** [comment]
I see whats going on, I attach the clients to the calltree buffer, and rust-analyzer thinks its a real file and wants to parse it. 

Im pretty sure I can just "not do that" lol. Will test it out in a bit and send a patch.

**Comment by ldelossa** [comment]
@IndianBoy42 fixed.
