### ISSUE TITLE
Error when opening call tree with :lua vim.lsp.buf.incoming_calls() and outgoing_calls()

### ISSUE THREAD

**Issue by quantum-booty** [ldelossa/calltree.nvim#20]
![image](https://user-images.githubusercontent.com/28958399/143225192-7f6ea05b-336c-4554-8de4-fe1c74645e2f.png)
This happens using the default calltree config:
```require('calltree').setup({ })```

**Comment by ldelossa** [comment]
@quantum-booty great catch, we were't handling non-icon configs well. Pushed the fix.
