### ISSUE TITLE
Better indentation and drop down indication

### ISSUE THREAD

**Issue by quantum-booty** [ldelossa/calltree.nvim#24]
Right now it is a bit difficult to know which item belongs to which node because the indentation is too small.
![image](https://user-images.githubusercontent.com/28958399/143403493-3ab6c8af-257c-4a2b-a11b-420e6c4b9844.png)
It would be nice to increase the indentation from one space to two spaces. It would also be nice to add support to indent guides: https://github.com/lukas-reineke/indent-blankline.nvim
Something like the nvim-tree:
![image](https://user-images.githubusercontent.com/28958399/143403469-6ca7583b-4d43-4d64-9f0e-e2e07b6261ba.png)
The indent lines can be right below the expanded arrow:
![image](https://user-images.githubusercontent.com/28958399/143404175-084d04f6-f162-4168-8a6f-995e0793ac8e.png)

Furthermore, isinstance and len function in the below screenshot doesn't have any children. It would be nice to not to have an arrow beside them to show this.
![image](https://user-images.githubusercontent.com/28958399/143403865-7aafe007-d4eb-4904-9394-deb284235d61.png)

**Comment by ldelossa** [comment]
Ill look into the indentation and indentation lines. 

To your last request, I believe the arrow being in ghe "drop down" position but no children displayed is a clear indicator there are no children at that node. Most drop down tree UIs ive seen do not remove the arrows when a node with no children is expanded.

**Comment by quantum-booty** [comment]
> Ill look into the indentation and indentation lines.
> 
> To your last request, I believe the arrow being in the "down" position but no children displayed is a clear indicator there are no children at that node. Most drop down tree UIs ive seen do not remove the arrows when a node with no children is expanded.

Currently the default arrow position is "right" even if a node doesn't have any children.
![image](https://user-images.githubusercontent.com/28958399/143490343-a913a653-3e63-4623-b6b4-c93e79d1af10.png)

**Comment by ldelossa** [comment]
But you haven't attempted to expand it yet. 

Every time you expand a symbol you're doing a new request to the LSP. It's closed right now because you haven't tried to resolve it. The UI doesn't know if there's children or not. Once you do try to expand it, the arrow will change to open. This is how it works in VSCode which I'm using as a model. 

Also, when you collapse the structure, and expand it again, we remove the history of the symbol. This is because, your code may have changed from the last time you made changes. You always need to expand a node to see if there's any children.

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/143512874-aa69e676-cbd8-46c7-985e-c78df3444bfd.png)

Implemented.

**Comment by ldelossa** [comment]
@quantum-booty - took me a bit to get there, but when this merged, leafs will no longer have any expansion icons next to them:

https://github.com/ldelossa/calltree.nvim/pull/60
