### ISSUE TITLE
Error when call vim.lsp.buf.outgoing_calls

### ISSUE THREAD

**Issue by leaxoy** [ldelossa/calltree.nvim#28]
![image](https://user-images.githubusercontent.com/8556349/144055479-2eda6e57-eb67-4c1d-b22e-908d90562e8f.png)

**Comment by ldelossa** [comment]
Hey there, can you give me some more details about your setup? What lsp and can you produce a python file which creates this error reliably?

**Comment by leaxoy** [comment]
Sure, https://github.com/leaxoy/v, here is my config repo, `lua/lsp/hierarchy.lua` setup this plugin, and `lua/lsp/init.lua` call `hierarchy` package

**Comment by ldelossa** [comment]
Thanks. Will look into this.

**Comment by ldelossa** [comment]
This is kinda odd, the "param" field is the original request that was sent to the LSP to start the call hierarchy request. If thats nil, no request can be made. 

What python language server are you using?

**Comment by leaxoy** [comment]
Pyright!

**Comment by leaxoy** [comment]
Should I register handler manual when attach lsp server?

**Comment by ldelossa** [comment]
Cant hurt to try, but setup function does this for you. Maybe there's a bug, but even so youre getting to calltrees handler so it's registered. I've restarted with pyright without this issue, do you have a python source file i can use to reproduce this,

**Comment by ldelossa** [comment]
@leaxoy can you attempt the same setup but make sure to call calltree's setup before the on-attach function ? I haven't seen it setup like this before. This could be the issue.

**Comment by leaxoy** [comment]
It can work after upgrading to nvim 0.6, thanks a lot

**Comment by ldelossa** [comment]
Awesome :)
