### ISSUE TITLE
Question: Difference between CTFocus and CTSwitch

### ISSUE THREAD

**Issue by LhKipp** [ldelossa/calltree.nvim#3]
Hi, thanks so much for this great plugin :)

I have a question regarding the CTSwitch command. The command is mentioned in the default keymaps section of the help page. However it is not documented. Is it any different than CTFocus?

Thanks 👍🏻

**Comment by ldelossa** [comment]
Ah, looks like I missed that in my docs. Ill update. 
CTSwitch will change the direction of the call tree for the given symbol (also focusing on the symbol)

Its really just a shortcut for a "CTJump" followed by calling the *opposite* call hierarchy method of the current tree, on the symbol you jumped too.

**Comment by LhKipp** [comment]
Great thanks :)
