### ISSUE TITLE
59d039b no longer opens calltree window

### ISSUE THREAD

**Issue by wilriker** [ldelossa/calltree.nvim#36]
With the latest commit 59d039b calltree.nvim no longer works for me. Going back one commit everything still works as intended.

When I open a go project and call `vim.lsp.buf.incoming_calls()` simply nothing happens. I debugged it until `ui.lua:136` where `ui_state.calltree_win` is `nil` and (for whatever reason) `vim.api.nvim_win_is_valid()` returns `true` for parameter `nil`. The subsequent `vim.api.nvim_set_current_win(nil)` simply does nothing.

What still works is the symboltree window but only if I open it **before** I call `vim.lsp.buf.incoming_calls()`. After that I cannot open symboltree again. It works as long as it is visible but I cannot reopen it once closed.

**Comment by ldelossa** [comment]
Cool, actually just ran into it this morning. Fix incoming.

**Comment by ldelossa** [comment]
@wilriker should be fixed.

**Comment by wilriker** [comment]
Thanks for the fast fix. I can confirm it works again!
