### ISSUE TITLE
Request: horizontal layout and file names

### ISSUE THREAD

**Issue by karlc1** [ldelossa/calltree.nvim#6]
Nice plugin! However, I find it hard to get an overview of callers without seeing the file name. Since it would be too crowded in a vertical panel, I suggest a third layout option to make it a quickfix-style window horizontally at the bottom with file names visible.

**Comment by ldelossa** [comment]
I was also planning to display details of the symbol via a popup window. I too find it a bit tough not having the file names around.

Your suggestion is good, and I think I'll do this. Will most likely do the pop-up window as well.

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/142552955-d1002757-265b-4d60-830b-b13d094b9633.png)

Here is what I'm thinking. 

If I can resolve a relative path I will, but if there are call references outside of "cwd" we'll just print the full path minus the LSP "file://" schema.

**Comment by karlc1** [comment]
Nice, well done!
